
import streamlit as st
st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab")
st.divider()
st.markdown("""
In this lab, you can explore the concepts of operational risk management through simulation. By adjusting parameters like the number of risk assessment units and the calculation method for residual risk, you can observe how inherent risk, control effectiveness, and other factors influence the overall risk profile.

### Key Concepts:

*   **Inherent Risk:** The level of risk before considering the impact of controls.
*   **Control Effectiveness:** The degree to which controls mitigate inherent risk.
*   **Residual Risk:** The level of risk remaining after considering the impact of controls.

### Instructions:

Use the sidebar to navigate to different pages of the application. Each page provides a different perspective on operational risk assessment. Experiment with the input parameters to see how they affect the results.

For example, on the "Data Generation and Validation" page, you can adjust the number of risk assessment units and whether to include time series data. On the "Residual Risk Calculation" page, you can select different calculation methods to see how they impact the residual risk rating. On the "Visualizations" page, you can explore the relationships between different risk factors through interactive plots.

**Important Considerations:**

*   The synthetic data generated by this application is for illustrative purposes only and should not be used for actual risk management decisions.
*   The residual risk calculation methods used in this application are simplified examples and may not be appropriate for all situations.

**Formulae:**

The basic formula for residual risk calculation is:

$$\text{Residual Risk} = f(\text{Inherent Risk}, \text{Control Effectiveness})$$

where $f$ can be either an additive function ('Basic' method) or a multiplicative/weighted function ('Weighted' method).

""")
# Your code starts here
page = st.sidebar.selectbox(label="Navigation", options=["Data Generation and Validation", "Residual Risk Calculation", "Visualizations"])
if page == "Data Generation and Validation":
    from application_pages.page1 import run_page1
    run_page1()
elif page == "Residual Risk Calculation":
    from application_pages.page2 import run_page2
    run_page2()
elif page == "Visualizations":
    from application_pages.page3 import run_page3
    run_page3()
# Your code ends
